# Generated by Django 5.0.2 on 2024-03-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название маршрута')),
                ('route_cities', models.CharField(max_length=150)),
                ('travel_time', models.CharField(max_length=50)),
                ('base_city', models.CharField(max_length=50)),
                ('bus', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=150)),
                ('working_hours', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.route', verbose_name='Маршрут')),
            ],
            options={
                'db_table': 'breweries',
            },
        ),
        migrations.CreateModel(
            name='Сountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('breweries', models.ManyToManyField(to='catalog.brewery')),
                ('routes', models.ManyToManyField(to='catalog.route')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
    ]
