# Generated by Django 5.0.2 on 2024-03-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_сountry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='image',
            field=models.ImageField(default='images/100.jpeg', upload_to='images/'),
        ),
    ]
