# Generated by Django 5.0.2 on 2024-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_brewery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='image',
            field=models.ImageField(default='100.jpeg', upload_to='images/'),
        ),
    ]
