# Generated by Django 5.0.2 on 2024-04-10 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_brewery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='url_r',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='image',
            field=models.ImageField(default='100.jpeg', upload_to=None),
        ),
    ]
