# Generated by Django 5.0.2 on 2024-03-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_cities',
            field=models.CharField(max_length=150, verbose_name='Города маршрута'),
        ),
    ]
