# Generated by Django 5.0.2 on 2024-03-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_сountry_breweries_brewery_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сountry',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
